FORMAT: 1A
HOST: http://localhost:3000/

# test-backend

Wiredcraft Back-end Developer Test


## Users Collection [/users]

### Create a New User [POST]

You can create a user by json object.

+ Request (application/json)

        {
            "name": "Jason Young",
            "dob": "1980-10-04",
            "address": "西南",
            "description": "Ncklm rtsx qgvmxkv pswzaouig vkvvd hhmvlbpik nrcu mvrn qpcc yyeetdasd emu vjpb. Gxdiut tpdefbqx slft tdmlwkr gmxsxk ccif sciyqmwle ibbe udubna uxytwqdv vlujhfqm juk mwrqtbd."
        }

+ Response 201 (application/json)

    + Body

            {
                "name": "Jason Young",
                "description": "Ncklm rtsx qgvmxkv pswzaouig vkvvd hhmvlbpik nrcu mvrn qpcc yyeetdasd emu vjpb. Gxdiut tpdefbqx slft tdmlwkr gmxsxk ccif sciyqmwle ibbe udubna uxytwqdv vlujhfqm juk mwrqtbd.",
                "dob": "1980-10-04",
                "address": "西南",
                "id": 2,
                "createdAt": "2020-08-06T19:30:11.473Z"
            }
            

## Users [/users/{user_id}]
+ Parameters
    + user_id - ID of the user
    
### Find a User by id [GET]

+ Response 200 (application/json)

    + Body

            {
                "name": "Jason Young",
                "description": "Ncklm rtsx qgvmxkv pswzaouig vkvvd hhmvlbpik nrcu mvrn qpcc yyeetdasd emu vjpb. Gxdiut tpdefbqx slft tdmlwkr gmxsxk ccif sciyqmwle ibbe udubna uxytwqdv vlujhfqm juk mwrqtbd.",
                "dob": "1980-10-04",
                "address": "西南",
                "id": 2,
                "createdAt": "2020-08-06T19:30:11.473Z"
            }
            
+ Response 404 (application/json)
    cannot find the user.
    + Body
    
            {
                "statusCode": 404,
                "message": "No User!",
                "error": "Not Found"
            }

### Update a User by id [POST]

+ Response 201 (text/plain)

### Delete a User by id [DELETE]

+ Response 200 (text/plain)